# Generated by Django 5.2 on 2026-01-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
