# Generated by Django 5.2 on 2026-01-28 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение в поддержку', 'verbose_name_plural': 'Сообщения в поддержку'},
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='support_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportrequest', verbose_name='Заявка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='support.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
