# Generated by Django 5.2 on 2026-02-05 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_alter_supportrequest_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка в поддержку",
                "verbose_name_plural": "Заявки в поддержку",
            },
        ),
        migrations.AlterField(
            model_name="supportmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_requests",
                to="support.userprofile",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01 00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("support", "Support"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
